// <auto-generated />
using AssignmentProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentProject.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230228064724_intial34564")]
    partial class intial34564
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AssignmentProject.Models.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IssueDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IssueId");

                    b.ToTable("issues");
                });

            modelBuilder.Entity("AssignmentProject.Models.Project", b =>
                {
                    b.Property<int>("projectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("projectid");

                    b.HasIndex("userid");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("AssignmentProject.Models.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssignmentProject.Models.Project", b =>
                {
                    b.HasOne("AssignmentProject.Models.User", "user")
                        .WithMany("project")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AssignmentProject.Models.User", b =>
                {
                    b.Navigation("project");
                });
#pragma warning restore 612, 618
        }
    }
}
